# Page settings

baseURL = "https://lazy-dev.github.io/adriano-cv/"
languageCode = "en"
title = "Resume"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-39926379-1"


[params]

    author = "Adriano Celentano"
    description = "DevOps Engineer with a fervent enthusiasm for software development"

    primaryColor = "#9c2b0e"
    textPrimaryColor = "#2c2626"

    [params.profile]
        enable = true
        name = "Adriano Celentano"
        tagline = "DevOps Engineer with a fervent enthusiasm for software development"
        avatar = "me.jpeg"

    [params.contact]
        enable = true
        location = "Chesham, Buckinghamshire"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:07716 532750"
        text = "07716 532750"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:adriano8899@gmail.com"
        text = "adriano8899@gmail.com"

    [params.summary]
        enable = true
        text = "Enthusiastic engineer with a strong focus on Linux-based systems, boasting a decade of expertise in conceptualizing and managing applications for businesses of varying sizes. Recognized for developing resilient, scalable systems that prioritize user-friendliness and ease of maintenance."


    [params.certification]
        enable = true

        [[params.certification.list]]
        course = "RedHat Certified Administrator"
        level = ""
        issued = "March 2012"

    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Cloud"
        [[params.skills.list.items]]
        details = "Amazon Web Services"

        [[params.skills.list]]
        title = "Programming"
        [[params.skills.list.items]]
        details = "Python"

        [[params.skills.list]]
        title = "Automation"
        [[params.skills.list.items]]
        details = "Ansible"
        [[params.skills.list.items]]
        details = "Terraform"

        [[params.skills.list]]
        title = "Containerisation"
        [[params.skills.list.items]]
        details = "Kubernetes"
        [[params.skills.list.items]]
        details = "Docker"

        [[params.skills.list]]
        title = "Operating Systems"
        [[params.skills.list.items]]
        details = "Linux"

    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Computer Gaming"
        [[params.interests.list]]
        name = "Linux"
        [[params.interests.list]]
        name = "Game Development"
        [[params.interests.list]]
        name = "Home Automation"
        [[params.interests.list]]
        name = "Blockchain applications"

    [params.education]
        enable = true
        [[params.education.list]]
        degree = "Bachelor's Computer Science"
        university = "Kingston University"
        dates = "2008 - 2011"

        [[params.education.list]]
        degree = "BTEC Software Development (level 2 & 3)"
        university = "West Thames College"
        dates = "2004 - 2006"

    [params.awards]
        enable = false

    [params.languages]
        enable = false


    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Senior DevOps Engineer"
        dates = "2022 - 2023"
        company = "Medispend"
        details = "Collaborated closely with the business on various strategic initiatives, including Microsoft 365 Security enhancements, internal tool development, architecture migration, cost optimization, and global platform expansion"
        [[params.experience.list.items]]
        details = "Microsoft 365 Security"
        [[params.experience.list.items]]
        details = "Internal tool development"
        [[params.experience.list.items]]
        details = "Architecture migration"
        [[params.experience.list.items]]
        details = "Cost reduction"

        [[params.experience.list]]
        title = "DevOps Engineer"
        dates = "2021 - 2022"
        company = "Realistic Games"
        url = "https://www.realisticgames.co.uk/"
        details = "Dedicated to spearheading platform modernization and providing steadfast support. Successfully introduced Kubernetes and multi-cloud capabilities to enhance operational efficiency"
        [[params.experience.list.items]]
        details = "Re-Architecture to Kubernetes"
        [[params.experience.list.items]]
        details = "Development of internal tooling"
        [[params.experience.list.items]]
        details = "Implementation of automated systems providing GitOps capabilities for Kubernetes (ArgoCD)"
        [[params.experience.list.items]]
        details = "Cost Optimisation"

        [[params.experience.list]]
        title = "DevOps Engineer"
        dates = "November 2020 - July 2021"
        company = "Vive (GH Bank)"
        url = "https://www.vive.co.uk"
        details = "Specialized engineer in cloud-based technologies and automation, dedicated to establishing a robust infrastructure for a novel digital bank. Led initiatives to revamp deployment systems, ensuring seamless CI/CD capabilities while prioritizing security"
        [[params.experience.list.items]]
        details = "Implementation of secure cloud native architecture"
        [[params.experience.list.items]]
        details = "Development of internal tooling"
        [[params.experience.list.items]]
        details = "Implementation of automated systems providing GitOps capabilities for Kubernetes and AWS"
        [[params.experience.list.items]]
        details = "Cost Optimisation"
        [[params.experience.list.items]]
        details = "Development of CI/CD platform for Spring based microservices"

        [[params.experience.list]]
        title = "DevOps Engineer"
        dates = "August 2020 - November 2020"
        company = "Metro Bank"
        url = "https://www.metrobankonline.co.uk/"
        details = "I became a member of the Metro team with the specific objective of enhancing the automated administration platform and playing a key role in a comprehensive IT modernization endeavor."
        [[params.experience.list.items]]
        details = "Cloud Architecture"
        [[params.experience.list.items]]
        details = "Automation to assist in the deployment of infrastructure"
        [[params.experience.list.items]]
        details = "Develop internal tooling to facilitate internal requirements"
        [[params.experience.list.items]]
        details = "Development of automated systems to reduce toil"



        [[params.experience.list]]
        title = "Linux Engineer | DevOps Engineer"
        dates = "November 2011 - November 2020"
        company = "Rackspace"
        url = "https://www.rackspace.com"
        details = "Offered comprehensive assistance to both internal and external clients, addressing a diverse range of solutions, including but not limited to LAMP, LNMP, and Cloud Computing."
        [[params.experience.list.items]]
        details = "Cloud Architecture"
        [[params.experience.list.items]]
        details = "On-Premise Architecture"
        [[params.experience.list.items]]
        details = "Mentorship of junior engineers"
        [[params.experience.list.items]]
        details = "Develop automation for Rackers to use on customer servers"
        [[params.experience.list.items]]
        details = "Development of automated systems to reduce toil"

    [params.projects]
        enable = false

    [params.information]
        enable = false

    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "https://github.com/dev-ace"
        title = "dev-ace"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "https://www.linkedin.com/in/adrianocelentano/"
        title = "adrianocelentano"
        [[params.social.list]]
        icon = "fas fa-file-pdf"
        url = "/resume.pdf"
        title = "PDF Copy"

    [params.footer]
        copyright = ""
