name: github pages

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 00 - checkout
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: 01 - Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.83.1'
        extended: true

    - name: 02 - Build
      run: hugo --minify

    - name: 03 - html to pdf
      uses: fifsky/html-to-pdf-action@master
      with:
        htmlFile: ./public/index.html
        outputFile: ./public/resume.pdf
        pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'

    - name: 04 - Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
